before_install:
  - sudo apt-get install -qq graphviz

rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_edge.gemfile

addons:
  code_climate:
    repo_token: 56d06c727f742b00720004db
